version: 2
registries:
  dockerhub:
    type: docker-registry
    url: https://registry.hub.docker.com
    username: ${{secrets.DOCKERHUB_USERNAME}}
    password: ${{secrets.DOCKERHUB_TOKEN}}
  github:
    type: git
    url: https://github.com
    username: ${{secrets.GH_USERNAME}}
    password: ${{secrets.GH_TOKEN}}
