name: Setup Enviroment
author: bill42362
description: Setup workflow enviroment variables.
runs:
  using: composite
  steps:
    - name: Prepare env variables
      shell: bash
      run: |
        echo "DOCKER_TAG_MASTER=${{ github.repository }}:master" >> $GITHUB_ENV
        echo "DOCKER_TAG_BRANCH=${{ github.repository }}:${{ env.GITHUB_REF_SLUG }}" >> $GITHUB_ENV
        echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
        echo "REPO_NAME=$(echo ${GITHUB_REPOSITORY#${{ github.actor }}/})" >> $GITHUB_ENV
