name: GitHub Page
on:
  push:
    branches:
      - "**"
    tags:
      - "v*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: get_env
        shell: bash
        run: echo "##[set-output name=docker_tag;]$(echo ${GITHUB_REPOSITORY}:${GITHUB_REF#refs/heads/})"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          target: build-client
          tags: ${{ steps.get_env.outputs.docker_tag }}-base
          cache-from: type=registry,ref=${{ steps.get_env.outputs.docker_tag }}-base
          cache-to: type=inline
          push: true
