name: GitHub Page
on:
  push:
    branches:
      - "**"
    tags:
      - "v*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Prepare env variables
        run: |
          echo "DOCKER_TAG_BASE=${{ github.repository }}:${{ env.GITHUB_REF_SLUG }}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Cache install-production
        uses: docker/build-push-action@v2
        with:
          target: install-production
          tags: ${{ env.DOCKER_TAG_BASE }}.install-production
          cache-from: type=registry,ref=${{ env.DOCKER_TAG_BASE }}.install-production
          cache-to: type=inline
          push: true
      - name: Cache install-develop
        uses: docker/build-push-action@v2
        with:
          target: install-develop
          tags: ${{ env.DOCKER_TAG_BASE }}.install-develop
          cache-from: |
            type=registry,ref=${{ env.DOCKER_TAG_BASE }}.install-production
            type=registry,ref=${{ env.DOCKER_TAG_BASE }}.install-develop
          cache-to: type=inline
          push: true
      - name: Cache build-client
        uses: docker/build-push-action@v2
        with:
          target: build-client
          tags: ${{ env.DOCKER_TAG_BASE }}.build-client
          cache-from: |
            type=registry,ref=${{ env.DOCKER_TAG_BASE }}.install-production
            type=registry,ref=${{ env.DOCKER_TAG_BASE }}.install-develop
            type=registry,ref=${{ env.DOCKER_TAG_BASE }}.build-client
          cache-to: type=inline
          push: true
